#!/usr/bin/env bash
# Save this file as /root/regen_id

svc_name="regen_id"
systemctl disable "${svc_name}.service"
rm -f "/etc/systemd/system/${svc_name}.service"

etc_id="/etc/machine-id"
var_id="/var/lib/dbus/machine-id"

echo -n > "${etc_id}"
systemd-machine-id-setup
systemd-machine-id-setup --commit

rm -f "${var_id}"
ln -s "${etc_id}" "${var_id}"

rm -f /etc/ssh/ssh_host_*_key{,.pub}
ssh-keygen -A

rm -f "/root/${svc_name}"
